src/main/java/com/espread/sys/model/SysDict.java
package com.espread.sys.model;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

@Table(name = "sys_Dict")
public class SysDict implements Serializable {

	@Id
    @GeneratedValue(generator = "UUID")
    private String dictId;

    private String dictPid;

    private String dictType;

    private String dictCode;

    private String dictName;

    private String dictFlag;

    private Integer dictSeq;

    private String description;

    private static final long serialVersionUID = 1L;

    public String getDictId() {
        return dictId;
    }

    public void setDictId(String dictId) {
        this.dictId = dictId == null ? null : dictId.trim();
    }

    public String getDictPid() {
        return dictPid;
    }

    public void setDictPid(String dictPid) {
        this.dictPid = dictPid == null ? null : dictPid.trim();
    }

    public String getDictType() {
        return dictType;
    }

    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    public String getDictCode() {
        return dictCode;
    }

    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    public String getDictName() {
        return dictName;
    }

    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    public String getDictFlag() {
        return dictFlag;
    }

    public void setDictFlag(String dictFlag) {
        this.dictFlag = dictFlag == null ? null : dictFlag.trim();
    }

    public Integer getDictSeq() {
        return dictSeq;
    }

    public void setDictSeq(Integer dictSeq) {
        this.dictSeq = dictSeq;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dictId=").append(dictId);
        sb.append(", dictPid=").append(dictPid);
        sb.append(", dictType=").append(dictType);
        sb.append(", dictCode=").append(dictCode);
        sb.append(", dictName=").append(dictName);
        sb.append(", dictFlag=").append(dictFlag);
        sb.append(", dictSeq=").append(dictSeq);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}

src/main/java/com/espread/sys/model/SysRoleResource.java
package com.espread.sys.model;

import java.io.Serializable;

public class SysRoleResource implements Serializable {

    private String roleId;

    private String resourceId;

    private static final long serialVersionUID = 1L;

    public SysRoleResource(String roleId, String resourceId) {
		super();
		this.roleId = roleId;
		this.resourceId = resourceId;
	}
	
    public String getRoleId() {
        return roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    public String getResourceId() {
        return resourceId;
    }

    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", resourceId=").append(resourceId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}

src/main/java/com/espread/sys/model/SysUserRole.java
package com.espread.sys.model;

import java.io.Serializable;

public class SysUserRole implements Serializable {

    private String userId;

    private String roleId;

    private static final long serialVersionUID = 1L;

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    public String getRoleId() {
        return roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}

src/main/java/com/espread/common/web/controller/BaseController.java
package com.espread.common.web.controller;

import com.espread.common.shiro.ShiroUser;
import com.espread.sys.model.SysUser;
import com.espread.sys.service.SysUserService;
import org.apache.shiro.SecurityUtils;
import org.apache.shiro.session.Session;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * 基础 controller
 * @author itdragons 2016-6-31 21:12:18
 */
public abstract class BaseController extends Controller{
    protected final Logger logger = LoggerFactory.getLogger(getClass());

    @Autowired
    private SysUserService sysUserService;
    
    /**
	 * 获取当前用户session
	 * @return session
	 */
	public static Session getSession(){
		Session session = SecurityUtils.getSubject().getSession();
		return session;
	}
    
    /**
	 * 获取当前用户对象shiro
	 * @return shirouser
	 */
	public static ShiroUser getShiroUser(){
		ShiroUser user = (ShiroUser) SecurityUtils.getSubject().getPrincipal();
		return user;
	}
	
    /**
     * 获取当前登录用户对象
     * @return
     */
    public SysUser getCurrentUser() {
        ShiroUser user = (ShiroUser) SecurityUtils.getSubject().getPrincipal();
        SysUser currentUser = sysUserService.selectByKey(user.userId);
        return currentUser;
    }
    
    /**
     * 获取当前登录用户id
     * @return
     */
    public String getUserId() {
        return getShiroUser().getUserId();
    }

    /**
     * 获取当前登录用户名
     * @return
     */
    public String getLoginName() {
        return getShiroUser().getLoginName();
    }
    
}

src/main/java/com/espread/sys/controller/LoginController.java
package com.espread.sys.controller;

import java.util.Date;
import java.util.HashMap;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import com.espread.sys.model.SysLog;
import com.espread.sys.model.SysUser;
import com.espread.sys.service.SysLogService;
import com.espread.sys.service.SysUserService;
import org.apache.shiro.SecurityUtils;
import org.apache.shiro.authc.DisabledAccountException;
import org.apache.shiro.authc.ExcessiveAttemptsException;
import org.apache.shiro.authc.ExpiredCredentialsException;
import org.apache.shiro.authc.IncorrectCredentialsException;
import org.apache.shiro.authc.LockedAccountException;
import org.apache.shiro.authc.UnknownAccountException;
import org.apache.shiro.subject.Subject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.espread.common.constant.Const;
import com.espread.common.constant.Global;
import com.espread.common.exception.CaptchaException;
import com.espread.common.shiro.UsernamePasswordCaptchaToken;
import com.espread.common.utils.StringUtils;
import com.espread.common.web.controller.BaseController;

/**
 * 登录退出
 * @author itdragons 2016-7-1 22:16:01
 */
@Controller
@RequestMapping(value = "{adminPath}")
public class LoginController extends BaseController {

	private Logger LOGGER = LoggerFactory.getLogger(LoginController.class);

    @Autowired
    private SysLogService sysLogService;

    @Autowired
    private SysUserService sysUserService;
	
    /**
     * 默认页面
     *
     * @param model
     * @return
     */
    @RequestMapping
    public String index(Model model) {
    	if (SecurityUtils.getSubject().isAuthenticated()) {
            return "sys/index";
        }
    	return "sys/login";
    }

    /**
     * GET 登录
     * @return {String}
     */
    @RequestMapping(value = "/login", method = RequestMethod.GET)
    public String login() {
        logger.info("GET请求登录");
        if (SecurityUtils.getSubject().isAuthenticated()) {
            return "redirect:" + Global.getAdminPath();
        }
        return "sys/login";
    }

    /**
     * POST 登录 shiro 写法
     *
     * @param username 用户名
     * @param password 密码
     * @return
     */
    @SuppressWarnings("unchecked")
	@RequestMapping(value = "/login", method = RequestMethod.POST)
    public Object loginPost(String username, String password, String captcha, Model model, HttpServletRequest request) {
    	logger.info("POST请求登录");
        String errMsg = "";
        UsernamePasswordCaptchaToken token = new UsernamePasswordCaptchaToken(username, password.toCharArray(), captcha, true, request.getRemoteHost());
        Subject user = SecurityUtils.getSubject();
		try {
			user.login(token);
		}catch(CaptchaException e){
			errMsg = "验证码错误";
		}catch (UnknownAccountException e) {
			errMsg = "用户名不存在";
		} catch (IncorrectCredentialsException ice) {
			errMsg = "密码错误";
		} catch (LockedAccountException e) {
			errMsg = "账户锁定状态";
		} catch (DisabledAccountException dax) {
			errMsg = "用户禁用状态";
		} catch (ExcessiveAttemptsException e) {
			errMsg = "登录失败次数过多";
		} catch (ExpiredCredentialsException eca) {
			errMsg = "用户凭证过期";
		} catch (RuntimeException e) {
			errMsg = "未知错误,请联系管理员";
		}finally{
	    	 if(StringUtils.isNotBlanks(errMsg)){
                 SysLog sysLog = new SysLog(Const.LOG_TYPE_LOGIN, "登陆失败，原因:" + errMsg);
                 sysLog.setLoginName(username);
                 sysLogService.save(request,false,sysLog);
	    		 model.addAttribute("msg", errMsg);
	    		 return "sys/login";
	    	 }
		}
        //登陆成功后
        // 1.更新登陆次数/最后登陆时间
        SysUser sysUser = getCurrentUser();
        sysUser.setLastvisitDate(new Date());
        sysUser.setLoginCount(sysUser.getLoginCount()!=null?sysUser.getLoginCount()+1:1);
        sysUserService.updateAll(sysUser);
		//2.Session中写入用户相关信息
		getSession().setAttribute(Const.SESSION_USER_ID, getUserId());//用户Id存入session中
		//3.当前用户Session 写入 ServletContext
		ServletContext application = request.getServletContext();//获取Servlet上下文环境
		HashMap<String,HttpSession> sessionMap = (HashMap<String, HttpSession>) application.getAttribute("sessions");
		HttpSession httpSession = request.getSession();
		sessionMap.put(getUserId(), httpSession); //SessionID 存入 ServletContext中 （key:用户Id value:Session ID）
		//保存日志
        LOGGER.info("sessions add[userId:{}]：" + httpSession.getId(), getUserId());
        SysLog sysLog = new SysLog(Const.LOG_TYPE_LOGIN, "登陆成功");
        sysLog.setLoginName(username);
        sysLogService.save(request,false,sysLog);
		return "redirect:" + Global.getAdminPath();
    }

    /**
     * 未授权
     * @return {String}
     */
    @RequestMapping(value = "/unauth")
    public String unauth(Model model) {
        if (SecurityUtils.getSubject().isAuthenticated()) {
            return "page/403";
        }
        return "sys/login";
    }

    /**
     * 退出
     * @return {Result}
     */
    @RequestMapping(value = "/logout")
    @ResponseBody
    public Object logout(Model model) {
        logger.info("安全退出,用户名:" + getLoginName());
        SecurityUtils.getSubject().logout();
        return resultSuccess("您已安全退出");
    }
}

src/main/java/com/espread/sys/controller/SysDictController.java
package com.espread.sys.controller;

import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.espread.common.utils.StringUtils;
import com.espread.common.web.controller.BaseController;
import com.espread.sys.model.SysDict;
import com.espread.sys.service.SysDictService;

/**
 * 字典管理
 * @author itdragons 2016-9-12 08:31:16
 */
@Controller
@RequestMapping("/sysDict")
public class SysDictController extends BaseController {

    @Autowired
    private SysDictService sysDictService;

    /**
     * 所有字典树
     * @return
     */
    @RequestMapping("/allTree/json")
    @ResponseBody
    public Object allTree() {
        return sysDictService.findDictAllTree(null);
    }
    
    /**
     * 字典管理页面
     * @return
     */
    @RequestMapping(method = RequestMethod.GET)
    public String manager() {
    	return "sys/sysDict";
    }

    /**
     * 字典管理列表
     * @return
     */
    @RequiresPermissions("sys:dict:view")
    @RequestMapping(value = "/treeGrid/json", method = RequestMethod.POST)
    @ResponseBody
    public Object treeGrid() {
        return sysDictService.findDictAllVo(null);
    }

    /**
     * 添加页面
     * @return
     */
    @RequiresPermissions("sys:dict:add")
    @RequestMapping("/addPage")
    public String addPage() {
        return "sys/sysDictAdd";
    }

    /**
     * 添加字典数据
     * @param sysDict
     * @return
     */
    @RequiresPermissions("sys:dict:add")
    @RequestMapping("/add")
    @ResponseBody
    public Object add(SysDict sysDict) {
		if (StringUtils.isBlanks(sysDict.getDictPid())) {
            sysDict.setDictPid(null);
		}
    	sysDictService.save(sysDict);
        return resultSuccess("添加成功！");
    }


    /**
     * 编辑字典页面
     * @param model
     * @param id
     * @return
     */
    @RequiresPermissions("sys:dict:edit")
    @RequestMapping("/editPage")
    public String editPage(Model model, String id) {
        SysDict sysDict = sysDictService.selectByKey(id);
        model.addAttribute("sysDict", sysDict);
        return "sys/sysDictEdit";
    }

    /**
     * 编辑字典
     * @param dict
     * @return
     */
    @RequiresPermissions("sys:dict:edit")
    @RequestMapping("/edit")
    @ResponseBody
    public Object edit(SysDict dict) {
		SysDict sysDict = sysDictService.selectByKey(dict.getDictId());
        if (sysDict != null) {
            sysDict.setDictPid(StringUtils.isBlanks(dict.getDictPid())?null:dict.getDictPid());
            sysDict.setDictCode(dict.getDictCode());
            sysDict.setDictCode(dict.getDictCode());
            sysDict.setDictName(dict.getDictName());
            sysDict.setDictType(dict.getDictType());
            sysDict.setDictSeq(dict.getDictSeq());
            sysDict.setDescription(dict.getDescription());
            //PID可能为空且有外键约束，所以update全部
            sysDictService.updateAll(sysDict);
        }
        return resultSuccess("编辑成功！");
    }

    /**
     * 删除字典
     * @param id
     * @return
     */
    @RequiresPermissions("sys:resource:del")
    @RequestMapping("/delete")
    @ResponseBody
    public Object delete(String id) {
        sysDictService.delete(id);
        return resultSuccess("删除成功！");
    }

}

src/main/java/com/espread/sys/controller/SysLogController.java
package com.espread.sys.controller;

import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.espread.common.constant.Const;
import com.espread.common.utils.ServletUtils;
import com.espread.common.web.PageInfo;
import com.espread.common.web.controller.BaseController;
import com.espread.sys.model.result.SysUserVo;
import com.espread.sys.service.SysDictService;
import com.espread.sys.service.SysLogService;

/**
 * 日志查询
 * @author itdragons 2016-09-17 18:02:23
 */
@Controller
@RequestMapping(value="sysLog")
public class SysLogController extends BaseController {
	
	@Autowired
	private SysLogService sysLogService;

	@Autowired
    private SysDictService sysDictService;
	
	/**
	 * 所有日志类型-tree
	 * @return
	 */
	@RequestMapping("/allTypeTree/json")
	@ResponseBody
	public Object allTypeTree() {
		return sysDictService.findDictAllTree(Const.DICT_TYPE_LOG_TYPE);
	}

	/**
	 * 日志查询页面
	 * @return
	 */
	@RequestMapping(method = RequestMethod.GET)
    public String manager() {
        return "sys/sysLog";
    }
	
	/**
	 * 日志列表
	 * @param page
	 * @param rows
	 * @param sort
	 * @param order
	 * @return
	 */
	@RequiresPermissions("sys:log:view")
	@RequestMapping(value = "/dataGrid/json", method = RequestMethod.POST)
	@ResponseBody
	public Object dataGrid(SysUserVo sysUserVo, Integer page, Integer rows, String sort, String order, HttpServletRequest request) {
		PageInfo pageInfo = new PageInfo(page, rows, sort, order);
		Map<String, Object> condition = ServletUtils.getParmFilter(request);
		pageInfo.setPageResult(sysLogService.findDataGrid(pageInfo, condition));
        return pageInfo;
	 }
}

src/main/webapp/WEB-INF/views/sys/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page import="com.espread.common.constant.Global"%>
<c:set var="ctx" value="${pageContext.request.contextPath}"/>
<%
	request.setAttribute("adminPath", Global.getAdminPath());
%>
<html>
	<head>
		<title>Espread后台管理</title>
		<script src="${ctx}/static/plugins/easyui/jquery.min.js"></script>
		<link rel="stylesheet" type="text/css" href="${ctx}/static/css/login.css" />
		<script type="text/javascript">
			$(function() {
				$("document").ready(function(){
					//防止在frame里面出现登录页面
					if(top.location != self.location){
						top.location.href=self.location.href;
					}
				});
			});
			var captcha;
			function refreshCaptcha(){
				document.getElementById("img_captcha").src="${ctx}/static/images/kaptcha.jpg?t=" + Math.random();
			}
		</script>
	</head>
	<body>
		<div class="main">
			<div class="login">
				<h1>Espread后台管理</h1>
				<div class="inset">
					<form id="loginForm" action="${ctx}${adminPath}/login" method="post">
						<div>
							<h2>${msg}</h2>
							<span><label>用户名</label></span>
							<span><input type="text" name="username" class="textbox" value="admin" ></span>
						</div>
						<div>
							<span><label>密码</label></span>
							<span><input type="password" name="password" class="password" value="111111"></span>
						</div>
						<div>
							<span><label>验证码</label></span>
									<span style="padding-top: 5px">
										<input type="text" name="captcha" class="text" value="" style="width: 50%;margin: 0px"/>
										<img alt="验证码" src="${ctx}/static/images/kaptcha.jpg" style="height:43px;width:39%;margin-left: 3px;vertical-align:bottom;" title="点击更换" id="img_captcha" onclick="javascript:refreshCaptcha();" />
									</span>
						</div>
						<div class="sign">
							<input type="submit" value="登录" class="submit" />
						</div>
					</form>
				</div>
			</div>
		</div>

		<div class="copy-right">
			<p>&copy; Copyright © 2016 power by espread</p>
		</div>
	</body>
</html>

src/main/webapp/WEB-INF/views/sys/sysDictEdit.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/views/include/global.jsp"%>
<script type="text/javascript">
    $(function() {
        $('#pid').combotree({
            url : '${ctx}/sysDict/allTree/json',
            parentField : 'pid',
            lines : true,
            panelHeight : 'auto',
            value : '${sysDict.dictPid}',
            onClick : function(node){
                if (node.attributes && node.attributes.dictType) {
                    $('#dictType').val(node.attributes.dictType);
                }
            }
        });

        $('#sysDictEditForm').form({
            url : '${ctx}/sysDict/edit',
            onSubmit : function() {
                progressLoad();
                var isValid = $(this).form('validate');
                if (!isValid) {
                    progressClose();
                }
                return isValid;
            },
            success : function(result) {
                progressClose();
                result = $.parseJSON(result);
                if (result.success) {
                    parent.$.modalDialog.openner_treeGrid.treegrid('reload');
                    parent.$.modalDialog.handler.dialog('close');
                    $.messager.show({
                        title : '提示',
                        msg : result.msg,
                        timeout : 1000
                    });
                } else {
                    parent.$.messager.alert('错误', result.msg, 'error');
                }
            }
        });
        $("#description").val('${sysDict.description}');
    });

    function openIconAllHtml(){
   		window.open("${staticPath}/icon/group/icon-all.html");
   	}

</script>
<div class="gridDiv">
    <form id="sysDictEditForm" method="post">
        <div class="gridDiv light-info">
            <div>注意：修改类型或参数，可能会导致系统数据异常，谨慎操作！</div>
        </div>
        <table class="grid">
            <tr>
                <td>参数</td>
                <td>
                    <input name="dictId" type="hidden"  value="${sysDict.dictId}" >
                    <input name="dictCode" id="dictCode" class="easyui-textbox" prompt="请输入参数名" value="${sysDict.dictCode}">
                </td>
                <td>名称</td>
                <td><input name="dictName" class="easyui-textbox" prompt="请输入名称" value="${sysDict.dictName}" data-options="required:true" ></td>
            </tr>
            <tr>
                <td>上级</td>
                <td><select id="pid" name="dictPid"></select>
                    <a class="easyui-linkbutton" href="javascript:void(0)" onclick="$('#pid').combotree('clear');" >清空</a></td>
                <td>类型</td>
                <td colspan="4"><input name="dictType" id="dictType" type="text" class="easyui-textbox" prompt="请输入类型名称" value="${sysDict.dictType}" data-options="required:true" ></td>
            </tr>
            <tr>
                <td>排序</td>
                <td><input name="dictSeq" class="easyui-numberspinner" value="${sysDict.dictSeq}" data-options="editable:false"></td>
            </tr>
            <tr>
                <td>描述</td>
                <td colspan="3"><input name="description" id="description" multiline="true" class="easyui-textbox" prompt="请输入描述信息"></input></td>
            </tr>
        </table>
    </form>
</div>

src/main/webapp/WEB-INF/views/sys/sysUserView.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/views/include/global.jsp"%>
<script type="text/javascript">
$(function() {

	<%-- 处理List对象 --%>
	var roleName;
	<c:forEach items="${userVo.roleList}" var="sysRole" varStatus="i">
		<c:choose>
	   		<c:when test="${i.index == 0}">
				roleName = "" + "${sysRole.roleName}";
			</c:when>
			<c:otherwise>
				roleName = roleName + "，" + "${sysRole.roleName}";
		    </c:otherwise>
		</c:choose>
	</c:forEach>

	$('#userEditForm').form({
        url : '${ctx}/sysUser/currentUserEdit',
        onSubmit : function() {
            progressLoad();
            var isValid = $(this).form('validate');
            if (!isValid) {
                progressClose();
            }
            return isValid;
        },
        success : function(result) {
            progressClose();
            result = $.parseJSON(result);
            if (result.success) {
                parent.$.modalDialog.handler.dialog('close');
                $.messager.show({
                    title : '提示',
                    msg : result.msg,
                    timeout : 1000
                });
            } else {
                $.messager.alert('错误', result.msg, 'error');
            }
        }
    });

    $('#roleNames').val(roleName);
    $('#sex').val('${userVo.sex}');
    $('#userStatus').val('${userVo.userStatus}');

});
</script>
<div class="easyui-layout" data-options="fit:true,border:false">
    <div class="gridDiv" data-options="region:'center',border:false">
        <form id="userEditForm" method="post">
            <div class="gridDiv light-info" >
                <div>支持修改部分信息</div>
            </div>
            <table class="grid">
                <tr>
                    <td>登录名</td>
                    <td>
                    	<input type="hidden" value="${userVo.userId}">
                    	<input class="easyui-textbox" data-options="readonly:true,iconCls:'icon-metro-lock'" value="${userVo.loginName}"/>
                    </td>
                    <td>姓名</td>
                    <td>
                    	<input class="easyui-textbox" data-options="readonly:true,iconCls:'icon-metro-lock'" value="${userVo.userName}"/>
                    </td>
                </tr>
                <tr>
                    <td>性别</td>
                    <td>
                        <select name="sex" id="sex" class="easyui-combobox" data-options="editable:false,panelHeight:'auto'">
                            <option value="1" selected="selected">男</option>
                            <option value="2" >女</option>
                        </select>
                    </td>
                    <td>登陆次数</td>
                    <td>
                        <input class="easyui-textbox" data-options="readonly:true,iconCls:'icon-metro-lock'" value="${userVo.loginCount}"/>
                    </td>
                </tr>
                <tr>
                    <td>部门</td>
                    <td>
                        <input class="easyui-textbox" data-options="readonly:true,iconCls:'icon-metro-lock'" value="${userVo.sysOrg.orgName}"/>
                    </td>
                	<td>用户状态</td>
                    <td>
                        <select id="userStatus" class="easyui-combobox" data-options="readonly:true,iconCls:'icon-metro-lock',editable:false,panelHeight:'auto'">
                                <option value="1">正常</option>
                                <option value="0">停用</option>
                        </select>
                    </td>
                </tr>
                <tr>
                	<td>角色</td>
                    <td colspan="3"><input id="roleNames" class="easyui-textbox" data-options="readonly:true,iconCls:'icon-metro-lock'"/></td>
                </tr>
                <tr>
                    <td>电话</td>
                    <td>
                        <input type="text" name="phone" class="easyui-numberbox" value="${userVo.phone}"/>
                    </td>
                     <td>Email</td>
                    <td>
                        <input type="text" name="email" class="easyui-textbox" value="${userVo.email}"/>
                    </td>
                </tr>
                <tr>
                    <td>地址</td>
                    <td colspan="3">
                    <input class="easyui-textbox" multiline="true" data-options="readonly:true,iconCls:'icon-metro-lock'" value="${userVo.address}" /></td>
                </tr>
                <tr>
                	<td>描述</td>
                    <td colspan="3">
                    	<input class="easyui-textbox" multiline="true" data-options="readonly:true,iconCls:'icon-metro-lock'" value="${userVo.description}"/>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>